name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
        id: release

    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      release-tag: ${{ steps.release.outputs.tag_name }}
      release-version: ${{ steps.release.outputs.version }}

  helm:
    needs:
      - release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release-created == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Run chart-releaser
        uses: bitdeps/helm-oci-charts-releaser@main
        with:
            oci_registry: ghcr.io/kubecloudscaler/charts
            oci_username: username
            oci_password: ${{ secrets.GITHUB_TOKEN }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
